### ISSUE TITLE
GitHub bridge slow to update metadata branch

### ISSUE THREAD

**Issue by talex5** [docker/datakit#213] opened 2016-07-27 13:46 UTC
I often see that the `metadata-x` branch (tracking GitHub) has new events pushed to it, but they don't get merged to `metadata` for a long time (minutes to hours).

**Comment by samoht** [comment] 2016-09-25 09:58
The initial cause of the problem is fixed, so closing this.

**Closed by samoht** 2016-09-25 09:58 UTC
Labels: area/github, kind/bug
